/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: negar (https://sketchfab.com/negar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/peach-d3ee1a643ddd45dc93695fcba465143f
Title: Peach
*/

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

const DEFAULT_SCALE = 0.01

export function PeachModel(props) {
	const { scale = DEFAULT_SCALE, ...rest } = props
	const { nodes, materials } = useGLTF('/scene.gltf')
	const groupRef = useRef()

	useFrame((_, delta) => {
		if (groupRef.current) {
			groupRef.current.rotation.y += delta * 0.5
			groupRef.current.rotation.x += delta * 0.5
		}
	})

	return (
		<group ref={groupRef} {...rest} dispose={null} scale={scale}>
			<mesh
				geometry={nodes.stem_StemColor_0.geometry}
				material={materials.StemColor}
				position={[0, 84.577, -4.798]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={[4, 4, 36.5]}
			/>
			<mesh
				geometry={nodes.Leaves_LeafColor_0.geometry}
				material={materials.LeafColor}
				position={[-35.047, 103.155, -8.601]}
				rotation={[-1.671, -0.131, -0.249]}
				scale={[43.899, 23.267, 3.326]}
			/>
			<mesh
				geometry={nodes.Peach_PeachColor_0.geometry}
				material={materials.PeachColor}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}
			/>
		</group>
	)
}

useGLTF.preload('/scene.gltf')
